name: WareWolf
version: '${project.version}'
main: net.tv.twitch.chrono_fish.warewolf.WareWolf
author: chrono_fish_SuteKa7
api-version: '1.20'
description: "This is a custom plugin for playing WareWolf"
commands:
  ww:
